name: Docker
on:
  schedule:
    # 定时任务，在每天的5点执行任务
    - cron: '40 10 * * *'

jobs:
  build:
    name: My Send
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'Install NPM dependencies'
        run: npm install axios

      - name: Run
        run: node index.js
